spring:
  profiles:
    active: ${active-profile}
  datasource:
    driver-class-name: ${database-driver-class}
    url: ${database-url}
    password: ${database-password}
    username: ${database-username}
server:
  servlet:
    context-path: /lena-shoes
app:
  file:
    bucket: D:\MyProjects\Works.Account\Online Shoe Store. Files storage
    product-file-not-found-path: src/main/resources/static/img/photo_not_found.svg