spring:
  profiles:
    active: ${active-profile}
  datasource:
    driver-class-name: ${database-driver-class}
    url: ${database-url}
    password: ${database-password}
    username: ${database-username}